<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="76813" started-at="2021-03-22T07:06:04 IST" finished-at="2021-03-22T07:07:21 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="76813" started-at="2021-03-22T07:06:04 IST" finished-at="2021-03-22T07:07:21 IST">
      <class name="testcases.Register_TC">
        <test-method status="PASS" signature="extentReportSetUp()[pri:0, instance:testcases.Register_TC@4d3167f4]" name="extentReportSetUp" is-config="true" duration-ms="133" started-at="2021-03-22T07:06:04 IST" finished-at="2021-03-22T07:06:04 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extentReportSetUp -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:testcases.Register_TC@4d3167f4]" name="setUp" is-config="true" duration-ms="5798" started-at="2021-03-22T07:06:05 IST" finished-at="2021-03-22T07:06:11 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="register_TC(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testcases.Register_TC@4d3167f4]" name="register_TC" duration-ms="68940" started-at="2021-03-22T07:06:11 IST" data-provider="TestData" finished-at="2021-03-22T07:07:20 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[anil]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[logistics]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[ak-22-03-2021-07-06-05@gmail.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[123456]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[123456]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Verify User Home Page expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Verify User Home Page expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at testcases.Register_TC.register_TC(Register_TC.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- register_TC -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:testcases.Register_TC@4d3167f4]" name="tearDown" is-config="true" duration-ms="1397" started-at="2021-03-22T07:07:20 IST" finished-at="2021-03-22T07:07:21 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=register_TC status=FAILURE method=Register_TC.register_TC(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testcases.Register_TC@4d3167f4] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.Register_TC -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
